name: Deploy to Prod

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd CV.MAKER-server
            docker-compose down
            git pull origin main
            docker-compose up --build -d
